s = set()
number = int(input("Enter numbers 1 : "))
s.add(int(number))
number = int(input("Enter numbers 2 : "))
s.add(int(number))
number = int(input("Enter numbers 3 : "))
s.add(int(number))
number= int(input("Enter numbers 4 : "))
s.add(int(number))
number = int(input("Enter numbers 5 : "))
s.add(int(number))
number = int(input("Enter numbers 6 : "))
s.add(int(number))
number = int(input("Enter numbers 7 : "))
s.add(int(number))
number = int(input("Enter numbers 8 : "))
s.add(int(number))

print(s)
